"""Initial migration

Revision ID: 7c58ba61c8d3
Revises: 
Create Date: 2025-12-10 06:38:54.266754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c58ba61c8d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tail_number', sa.String(), nullable=False),
    sa.Column('aircraft_type', sa.String(), nullable=False),
    sa.Column('availability', sa.JSON(), nullable=True),
    sa.Column('maintenance_schedule', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aircraft_id'), 'aircraft', ['id'], unique=False)
    op.create_index(op.f('ix_aircraft_tail_number'), 'aircraft', ['tail_number'], unique=True)
    op.create_table('simulators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulator_id', sa.String(), nullable=False),
    sa.Column('simulator_type', sa.String(), nullable=False),
    sa.Column('availability', sa.JSON(), nullable=True),
    sa.Column('maintenance_schedule', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulators_id'), 'simulators', ['id'], unique=False)
    op.create_index(op.f('ix_simulators_simulator_id'), 'simulators', ['simulator_id'], unique=True)
    op.create_table('training_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_name', sa.String(), nullable=False),
    sa.Column('requirement_type', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_name')
    )
    op.create_index(op.f('ix_training_requirements_id'), 'training_requirements', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'SCHEDULER', 'PILOT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('FLIGHT', 'SIMULATOR', name='eventtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'EFFECTIVE', 'CANCELLED', name='eventstatus'), nullable=True),
    sa.Column('aircraft_id', sa.Integer(), nullable=True),
    sa.Column('simulator_id', sa.Integer(), nullable=True),
    sa.Column('crew_composition', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ),
    sa.ForeignKeyConstraint(['simulator_id'], ['simulators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)
    op.create_table('pilots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('call_sign', sa.String(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('qualifications', sa.JSON(), nullable=True),
    sa.Column('availability', sa.JSON(), nullable=True),
    sa.Column('time_off', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_pilots_call_sign'), 'pilots', ['call_sign'], unique=True)
    op.create_index(op.f('ix_pilots_id'), 'pilots', ['id'], unique=False)
    op.create_table('schedule_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_number')
    )
    op.create_index(op.f('ix_schedule_versions_id'), 'schedule_versions', ['id'], unique=False)
    op.create_table('currency_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('currency_type', sa.String(), nullable=False),
    sa.Column('last_completed_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_records_id'), 'currency_records', ['id'], unique=False)
    op.create_table('event_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_assignments_id'), 'event_assignments', ['id'], unique=False)
    op.create_table('pilot_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('qualification_status', sa.Enum('CMR', 'BMC', 'NOT_QUALIFIED', name='qualificationstatus'), nullable=True),
    sa.Column('evaluation_month', sa.Date(), nullable=False),
    sa.Column('requirements_met', sa.JSON(), nullable=True),
    sa.Column('deficiencies', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pilot_id', 'evaluation_month', name='uq_pilot_evaluation_month')
    )
    op.create_index(op.f('ix_pilot_status_evaluation_month'), 'pilot_status', ['evaluation_month'], unique=False)
    op.create_index(op.f('ix_pilot_status_id'), 'pilot_status', ['id'], unique=False)
    op.create_index(op.f('ix_pilot_status_pilot_id'), 'pilot_status', ['pilot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pilot_status_pilot_id'), table_name='pilot_status')
    op.drop_index(op.f('ix_pilot_status_id'), table_name='pilot_status')
    op.drop_index(op.f('ix_pilot_status_evaluation_month'), table_name='pilot_status')
    op.drop_table('pilot_status')
    op.drop_index(op.f('ix_event_assignments_id'), table_name='event_assignments')
    op.drop_table('event_assignments')
    op.drop_index(op.f('ix_currency_records_id'), table_name='currency_records')
    op.drop_table('currency_records')
    op.drop_index(op.f('ix_schedule_versions_id'), table_name='schedule_versions')
    op.drop_table('schedule_versions')
    op.drop_index(op.f('ix_pilots_id'), table_name='pilots')
    op.drop_index(op.f('ix_pilots_call_sign'), table_name='pilots')
    op.drop_table('pilots')
    op.drop_index(op.f('ix_events_start_time'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_training_requirements_id'), table_name='training_requirements')
    op.drop_table('training_requirements')
    op.drop_index(op.f('ix_simulators_simulator_id'), table_name='simulators')
    op.drop_index(op.f('ix_simulators_id'), table_name='simulators')
    op.drop_table('simulators')
    op.drop_index(op.f('ix_aircraft_tail_number'), table_name='aircraft')
    op.drop_index(op.f('ix_aircraft_id'), table_name='aircraft')
    op.drop_table('aircraft')
    # ### end Alembic commands ###
